name: AU-all

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Explore environment
        run: |
          gci
          Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version
          $PSVersionTable
          git --version
          choco --version
      
      - name: Install AU
        run: |
          git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
          . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version

      - name: Run AU update_all
        run: .\update_all.ps1

      - name: Zip AU results
        run: 7z a au_temp.zip $Env:TEMP\chocolatey\au\*
        if: ${{ always() }} # even if build fails

      - name: Upload results
        uses: actions/upload-artifact@v2.2.2
        with:
          name: results
          path: |
            update_info.xml
            Update-AUPackages.md
            au_temp.zip
        if: ${{ always() }} # even if build fails
